/**
 * One-time (idempotent) seed for the `booths` collection.
 *
 * Pulls the canonical booth list from
 * `src/lib/floorPlan/booth-numbers.generated.ts` (generated by
 * `scripts/brand-floor-plan.mjs` off the SVG) and creates a Booth record
 * for every number with `status: 'available'`. Existing records are left
 * alone — safe to re-run after the SVG gains new booths.
 *
 * Run:  node --env-file=.env.local --import tsx src/scripts/seed-booths.ts
 *   (or the npm script alias `npm run seed:booths`)
 *
 * Preconditions:
 *   - .env.local with DATABASE_URI + PAYLOAD_SECRET
 *   - Booths collection registered in src/payload.config.ts (it is)
 *   - public/images/floor-plan.svg has been regenerated at least once
 */

import { getPayload } from 'payload'
import config from '../payload.config'
import { BOOTH_NUMBERS } from '../lib/floorPlan/booth-numbers.generated'

async function main() {
  const payload = await getPayload({ config })

  if (BOOTH_NUMBERS.length === 0) {
    console.log(
      '[seed-booths] booth-numbers.generated.ts is empty — re-run\n' +
        '              `node scripts/brand-floor-plan.mjs` first.',
    )
    process.exit(0)
  }

  console.log(`[seed-booths] Found ${BOOTH_NUMBERS.length} booths in SVG.`)

  let created = 0
  let skipped = 0
  let errored = 0

  for (const number of BOOTH_NUMBERS) {
    try {
      const existing = await payload.find({
        collection: 'booths',
        where: { boothNumber: { equals: number } },
        limit: 1,
        depth: 0,
      })

      if (existing.docs.length > 0) {
        skipped++
        continue
      }

      await payload.create({
        collection: 'booths',
        data: {
          boothNumber: number,
          status: 'available',
        },
      })
      created++
    } catch (err) {
      errored++
      console.error(`[seed-booths] ${number}: error`, err instanceof Error ? err.message : err)
    }
  }

  console.log(
    `[seed-booths] Done. created=${created}, skipped=${skipped}, errored=${errored}`,
  )
  process.exit(errored > 0 ? 1 : 0)
}

main().catch((err) => {
  console.error('[seed-booths] Fatal:', err)
  process.exit(1)
})
